import React, { useState } from 'react';
import { Radio, Download, CloudLightning, RefreshCw, CheckCircle, Search, AlertCircle } from 'lucide-react';

export const AlbumReceiver = ({ onImportJsonData, setActiveTab }) => {
  const [albumCode, setAlbumCode] = useState('');
  const [isFetching, setIsFetching] = useState(false);
  const [fetchMessage, setFetchMessage] = useState(null);

  // Simulated remote database of client selections
  const remoteAlbums = [
    {
      title: "Sophia & Liam Wedding",
      code: "SG-Sophia-Wedding",
      client: "Sophia & Liam",
      date: "May 30, 2026",
      status: "Selection Submitted",
      selectionsCount: 24,
      totalCount: 95,
      // The exact JSON selections generated by this client
      jsonData: {
        galleryTitle: "Sophia & Liam Wedding",
        clientName: "Sophia & Liam",
        clientNotes: "Please crop DSC_003 closer and apply natural look editing, thanks!",
        submissionDate: "2026-05-30T16:54:12Z",
        totalImages: 95,
        selectedCount: 24,
        selections: [
          { fileName: "DSC_001.jpg", selected: true, rotation: 0 },
          { fileName: "DSC_002.jpg", selected: false, rotation: 0 },
          { fileName: "DSC_003.jpg", selected: true, rotation: 90 },
          { fileName: "DSC_004.jpg", selected: false, rotation: 0 },
          { fileName: "DSC_005.jpg", selected: true, rotation: 0 },
          { fileName: "DSC_006.jpg", selected: true, rotation: 180 }
        ]
      }
    },
    {
      title: "Emma Graduation Proofs",
      code: "SG-Emma-Grad",
      client: "Emma Watson",
      date: "May 28, 2026",
      status: "Pending client selections",
      selectionsCount: 0,
      totalCount: 45,
      jsonData: null
    },
    {
      title: "Product Catalog Fall 2026",
      code: "SG-Prod-Fall",
      client: "UrbanWear Team",
      date: "May 25, 2026",
      status: "Selections Completed",
      selectionsCount: 85,
      totalCount: 120,
      jsonData: {
        galleryTitle: "Product Catalog Fall 2026",
        clientName: "UrbanWear Team",
        clientNotes: "Please remove the background shadow on all selected catalogs.",
        submissionDate: "2026-05-25T11:20:00Z",
        totalImages: 120,
        selectedCount: 3,
        selections: [
          { fileName: "PROD_001.jpg", selected: true, rotation: 0 },
          { fileName: "PROD_002.jpg", selected: true, rotation: 0 },
          { fileName: "PROD_003.jpg", selected: true, rotation: 0 }
        ]
      }
    }
  ];

  const handleFetchCode = (e) => {
    e.preventDefault();
    if (!albumCode.trim()) return;

    setIsFetching(true);
    setFetchMessage(null);

    // Simulate network delay
    setTimeout(() => {
      const match = remoteAlbums.find(
        a => a.code.toLowerCase() === albumCode.trim().toLowerCase()
      );

      if (match) {
        if (match.status === "Pending client selections") {
          setFetchMessage({
            type: 'warning',
            text: `Album "${match.title}" found, but the client has not submitted their selections yet.`
          });
        } else {
          setFetchMessage({
            type: 'success',
            text: `Successfully fetched selections for "${match.title}"!`,
            album: match
          });
        }
      } else {
        setFetchMessage({
          type: 'error',
          text: `No active cloud gallery found for code "${albumCode}". Please verify spelling.`
        });
      }
      setIsFetching(false);
    }, 1500);
  };

  const handleSyncToMatcher = (album) => {
    if (!album.jsonData) return;
    onImportJsonData(album.jsonData);
    setActiveTab('process'); // Redirect directly to Matcher tab
    alert(`Success: Synced remote selection for "${album.title}" directly to the Selection Matcher!`);
  };

  return (
    <div className="space-y-8 animate-fade-in">
      
      {/* Top Banner */}
      <div className="bg-gradient-to-r from-indigo-950/40 via-purple-950/20 to-slate-950 border border-slate-900 rounded-3xl p-8 flex flex-col md:flex-row items-center justify-between gap-6 backdrop-blur-xl">
        <div className="space-y-2">
          <div className="w-11 h-11 rounded-xl bg-indigo-500/10 text-indigo-400 flex items-center justify-center">
            <Radio className="animate-pulse" size={22} />
          </div>
          <h3 className="font-extrabold text-xl text-white">Album Cloud Receiver</h3>
          <p className="text-sm text-slate-400 max-w-xl">
            Retrieve selection sheets submitted by your clients over-the-air. Enter the Album Code or select from your active cloud sessions below to import immediately.
          </p>
        </div>

        {/* Sync form */}
        <form onSubmit={handleFetchCode} className="w-full md:w-auto flex flex-col sm:flex-row gap-3 min-w-[320px]">
          <div className="relative flex-1">
            <input 
              type="text" 
              value={albumCode}
              onChange={e => setAlbumCode(e.target.value)}
              placeholder="e.g. SG-Sophia-Wedding" 
              className="w-full bg-slate-950 border border-slate-900 rounded-xl pl-10 pr-4 py-3 text-sm text-white placeholder-slate-600 focus:outline-none focus:border-indigo-500 transition-colors uppercase font-mono tracking-wider"
            />
            <Search size={16} className="absolute left-3.5 top-3.5 text-slate-600" />
          </div>
          <button
            type="submit"
            disabled={isFetching}
            className="px-6 py-3 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-900 disabled:text-slate-600 text-white rounded-xl font-bold text-sm shadow-lg shadow-indigo-600/10 transition-all duration-200 cursor-pointer flex items-center justify-center gap-2 shrink-0"
          >
            {isFetching ? (
              <>
                <RefreshCw size={16} className="animate-spin" />
                Connecting...
              </>
            ) : (
              <>
                <CloudLightning size={16} />
                Fetch Selections
              </>
            )}
          </button>
        </form>
      </div>

      {/* Fetch Results Banner */}
      {fetchMessage && (
        <div className={`p-5 rounded-2xl border animate-fade-in ${
          fetchMessage.type === 'success' ? 'bg-emerald-950/20 border-emerald-900/60' :
          fetchMessage.type === 'warning' ? 'bg-amber-950/20 border-amber-900/60' :
          'bg-rose-950/20 border-rose-900/60'
        }`}>
          <div className="flex items-start gap-4">
            <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${
              fetchMessage.type === 'success' ? 'bg-emerald-500/10 text-emerald-400' :
              fetchMessage.type === 'warning' ? 'bg-amber-500/10 text-amber-400' :
              'bg-rose-500/10 text-rose-400'
            }`}>
              {fetchMessage.type === 'success' ? <CheckCircle size={18} /> : <AlertCircle size={18} />}
            </div>
            <div className="flex-1">
              <h4 className={`font-bold text-sm ${
                fetchMessage.type === 'success' ? 'text-emerald-400' :
                fetchMessage.type === 'warning' ? 'text-amber-400' :
                'text-rose-400'
              }`}>{fetchMessage.type === 'success' ? 'Success' : fetchMessage.type === 'warning' ? 'Awaiting Selection' : 'Error'}</h4>
              <p className="text-xs text-slate-300 mt-1">{fetchMessage.text}</p>
              
              {fetchMessage.type === 'success' && (
                <button
                  onClick={() => handleSyncToMatcher(fetchMessage.album)}
                  className="mt-4 inline-flex items-center gap-2 bg-emerald-500 hover:bg-emerald-600 text-slate-950 text-xs font-bold px-4 py-2.5 rounded-lg transition-all duration-200 cursor-pointer shadow-lg shadow-emerald-500/10"
                >
                  <Download size={13} />
                  Load into Selection Matcher
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Cloud Sessions Table */}
      <div className="bg-slate-900/40 border border-slate-900 rounded-3xl p-6 backdrop-blur-xl">
        <h4 className="font-extrabold text-base text-white mb-6">Active Cloud Gallery Sessions</h4>
        
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="border-b border-slate-900 text-slate-500 uppercase tracking-wider font-bold">
                <th className="pb-4">Session Name</th>
                <th className="pb-4">Album Code</th>
                <th className="pb-4">Creation Date</th>
                <th className="pb-4">Status</th>
                <th className="pb-4 text-center">Selections</th>
                <th className="pb-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-900/50 text-slate-300">
              {remoteAlbums.map((album, idx) => (
                <tr key={idx} className="hover:bg-slate-900/20 transition-colors">
                  <td className="py-4 font-bold text-white">{album.title}</td>
                  <td className="py-4 font-mono font-bold text-slate-400">{album.code}</td>
                  <td className="py-4 text-slate-500">{album.date}</td>
                  <td className="py-4">
                    <span className={`px-2.5 py-1 rounded-full text-[10px] font-bold border ${
                      album.status.includes('Submitted') || album.status.includes('Completed')
                        ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/10'
                        : 'bg-amber-500/10 text-amber-400 border-amber-500/10'
                    }`}>
                      {album.status}
                    </span>
                  </td>
                  <td className="py-4 text-center font-bold text-slate-300">
                    {album.selectionsCount > 0 ? `${album.selectionsCount} Selected` : '—'}
                  </td>
                  <td className="py-4 text-right">
                    {album.jsonData ? (
                      <button
                        onClick={() => handleSyncToMatcher(album)}
                        className="inline-flex items-center gap-1.5 bg-indigo-500/10 border border-indigo-500/20 hover:bg-indigo-600 hover:text-white transition-all text-indigo-400 font-bold px-3 py-1.5 rounded-lg cursor-pointer"
                      >
                        <Download size={12} />
                        Sync Matcher
                      </button>
                    ) : (
                      <button
                        disabled
                        className="inline-flex items-center gap-1.5 bg-slate-950 border border-slate-900 text-slate-600 font-bold px-3 py-1.5 rounded-lg cursor-not-allowed"
                      >
                        Awaiting Client
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
};

export default AlbumReceiver;
